### ISSUE TITLE
`packageLicenseOverride` doesn't work when using `check-licenses` command

### ISSUE THREAD

**Issue by Matthiee** [rufman/license_checker#35]
I have the following config: 

``` yaml
permittedLicenses:
  - Apache

packageLicenseOverride:
  rxdart: Apache
```

And a direct dependency on https://pub.dev/packages/rxdart

Expected output: 
` rxdart  Apache`

Actual output:
`rxdart unknown-license`

Current workaround:

Updating my config file with
```yaml
approvedPackages:
  unknown-license:
    - rxdart # https://github.com/ReactiveX/rxdart/blob/58c82c0eefcea76b131de0d445fa24467ae58c47/LICENSE
```
